version: '3.8'
services:
  julia-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: julia-app
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    environment:
      - JULIA_NUM_THREADS=auto